---
pipeline:
  deploy:
    image: cschlosser/drone-ftps
    hostname: seznamovak.pedf.cuni.cz:21
    secrets: [ftp_username, ftp_password]
    secure: true
    verify: false # Certificate is self-signed
    dest_dir: /www
    exclude:
      - ^\.git/$
      - ^\.gitignore$
      - ^\.drone.yml$
